{{- if .Values.sso.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dmp.fullname" . }}-sso-frontend
  labels:
    {{- include "dmp.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sso-frontend
spec:
  replicas: {{ .Values.sso.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "dmp.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: sso-frontend
  template:
    metadata:
      labels:
        {{- include "dmp.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: sso-frontend
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: sso-frontend
          image: {{ include "dmp.image" (dict "imageRoot" .Values.sso.frontend.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.sso.frontend.image.pullPolicy }}
          {{- if .Values.sso.frontend.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.sso.frontend.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.sso.frontend.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.sso.frontend.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.sso.config.enabled }}
          envFrom:
            - configMapRef:
                name: {{ include "dmp.fullname" . }}-sso-config
          {{- end }}
          ports:
            {{- range $key, $value := .Values.sso.frontend.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value }}
              protocol: TCP
            {{- end }}
          {{- if and .Values.sso.config.enabled .Values.sso.config.files }}
          volumeMounts:
            - name: sso-config-volume
              mountPath: {{ .Values.sso.config.mountPath }}
          {{- end }}
      {{- if and .Values.sso.config.enabled .Values.sso.config.files }}
      volumes:
        - name: sso-config-volume
          configMap:
            name: {{ include "dmp.fullname" . }}-sso-config
            items:
            {{- range $key, $value := .Values.sso.config.files }}
              - key: {{ $key }}
                path: {{ $key }}
            {{- end }}
      {{- end }}
{{- end }}
