apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dmp.fullname" . }}-sso-env
  labels:
    {{- include "dmp.labels.standard" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.sso.extraSecretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
