{{- if .Values.sso.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sso.serviceAccountName" . }}
  labels:
    {{- include "dmp.labels.standard" . | nindent 4 }}
  {{- if .Values.sso.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.sso.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
