{{- if and .Values.sso.ingress.enabled .Values.sso.ingress.tlsSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dmp.fullname" . }}-sso-tls
  labels:
    {{- include "dmp.labels.standard" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.sso.ingress.tlsSecret.cert | b64enc }}
  tls.key: {{ .Values.sso.ingress.tlsSecret.key | b64enc }}
{{- end }}
