{{- if .Values.sso.socket.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dmp.fullname" . }}-sso-socket
  labels:
    {{- include "dmp.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sso-socket
spec:
  replicas: {{ .Values.sso.socket.replicaCount }}
  selector:
    matchLabels:
      {{- include "dmp.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: sso-socket
  template:
    metadata:
      labels:
        {{- include "dmp.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: sso-socket
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: sso-socket
          image: {{ include "dmp.image" (dict "imageRoot" .Values.sso.socket.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.sso.socket.image.pullPolicy }}
          ports:
            {{- range $key, $value := .Values.sso.socket.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value }}
              protocol: TCP
            {{- end }}
{{- end }}
